### ISSUE TITLE
Missing: Project license

### ISSUE THREAD

**Issue by drewrisinger** [OxfordIonTrapGroup/entangler-core#1]
Hello @dnadlinger @cjbe,
I'm interested in working on and extending this code, but there is no attached license. Can you please choose & publish an open-source license for this project?

I suggest either the MIT license or the GNUGPLv3, though you can choose for yourself at https://choosealicense.com

Thank you!
Drew Risinger
UMD

**Comment by drewrisinger** [comment]
ping @dnadlinger @cjbe

**Comment by cjbe** [comment]
Oops - missed this first time around. I will leave it to @dnadlinger to choose his favourite license...

**Comment by dnadlinger** [comment]
Ah, apologies for the hold-up; GPLv3 it is.

**Comment by drewrisinger** [comment]
Thank you!
